[package]
name = "cc-wired"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cc-wired"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
cc-wired-client = { path = "../client", version = "0.1.0" }
cc-wired-server = { path = "../server", version = "0.1.0" }
clap = { version = "4.6.6", features = ["derive"] }
