[package]
name = "cc-wired-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.15.0"
actix-ws = "0.4.0"
config = "0.15.25"
env_logger = "0.11.11"
futures-util = "0.3.34"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "sync"] }
